id: AD2D4DDD2
title: Prayer for the Long Life of Kyabgön Sakya Trichen
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:21:41.197173
  last_modified_at: 2022-03-01 00:21:41.197198
